#!/usr/bin/env python3
"""Install the kit once per user, for whichever agent harnesses you use.

    kit install --for codex,opencode      install for these harnesses
    kit install --detect                  install for every harness found on this machine
    kit doctor                            show what each harness will see
    kit uninstall [--for codex]           remove exactly what was installed (default: all)
    kit clean-project /path/to/app        remove an old per-project mirror (.opencode/.cursor/.claude)
    kit models show|discover|probe|set|report    which model each kit role runs on, per harness
    kit loop run|status /path/to/app      drive agent pull requests to ready-for-human

Skills live in one place per harness family, never inside a project. Claude Code installs
as the managed plugin; every other harness gets the skills linked from a generated build
under ~/.flutter-kit/build, plus its own agents, commands and hooks in the shape it reads.
install/harnesses.json is the registry of paths; ~/.flutter-kit/installed.json records
everything written, so uninstall removes exactly that and nothing of yours.

The kit names no models. install/roles.json says what each role needs; the configure-models
skill picks models the user can actually reach and saves them with `kit models set`, which
writes ~/.flutter-kit/models.json and re-pins every installed harness.

Environment: FLUTTER_KIT_HOME (default ~/.flutter-kit), HOME (tests point it elsewhere),
FLUTTER_KIT_SKIP_CLI=1 (never shell out to `claude`; tests set it).
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys

KIT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = json.loads((KIT / "install/harnesses.json").read_text())
HARNESSES = {h["id"]: h for h in REGISTRY["harnesses"]}
ROLES = json.loads((KIT / "install/roles.json").read_text())
HOME = pathlib.Path(os.environ.get("HOME", str(pathlib.Path.home())))
STATE = pathlib.Path(os.environ.get("FLUTTER_KIT_HOME", str(HOME / ".flutter-kit")))
BUILD = STATE / "build"
RECORD = STATE / "installed.json"
MODELS = STATE / "models.json"
EFFORTS = {"low", "medium", "high", "xhigh", "max", "ultra"}
HOOK_MARK = "kit-hook.py"
GENERATED = "<!-- Generated by flutter-engineering-kit (scripts/kit.py). Re-run `kit install` instead of editing. -->"


# ---------------------------------------------------------------- helpers

def expand(p: str) -> pathlib.Path:
    return HOME / p[2:] if p.startswith("~/") else pathlib.Path(p)


def kit_ref() -> pathlib.Path:
    """The path installed files point at. Through ~/.flutter-kit/current when this run comes
    from there, so `kit update` re-points one symlink instead of rewriting every hook."""
    current = STATE / "current"
    if current.is_symlink() and current.resolve() == KIT:
        return current
    return KIT


def frontmatter(text: str) -> tuple[str, str]:
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    return (m.group(1), m.group(2)) if m else ("", text)


def field(front: str, key: str) -> str:
    m = re.search(rf"^{key}:\s*(.+)$", front, re.M)
    return m.group(1).strip().strip('"') if m else ""


def skills() -> list[pathlib.Path]:
    return sorted(p.parent for p in (KIT / "skills").glob("*/SKILL.md"))


def user_invoked() -> list[str]:
    return [d.name for d in skills()
            if "disable-model-invocation: true" in frontmatter((d / "SKILL.md").read_text())[0]]


def agents() -> list[pathlib.Path]:
    return sorted(p for p in (KIT / "agents").glob("*.md") if p.name != "README.md")


def read_json(path: pathlib.Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return json.loads(strip_jsonc(path.read_text()))


def write_json(path: pathlib.Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def strip_jsonc(text: str) -> str:
    out, i, n, in_str, esc = [], 0, len(text), False, False
    while i < n:
        c = text[i]
        if in_str:
            out.append(c)
            esc = (not esc) and c == "\\"
            if c == '"' and not esc:
                in_str = False
            i += 1
        elif c == '"':
            in_str = True
            out.append(c)
            i += 1
        elif text.startswith("//", i):
            while i < n and text[i] != "\n":
                i += 1
        elif text.startswith("/*", i):
            end = text.find("*/", i + 2)
            i = n if end < 0 else end + 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def link(src: pathlib.Path, dest: pathlib.Path, written: list[str]) -> None:
    """Symlink dest -> src. Refuses to replace anything that is not already our link."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.is_symlink():
        dest.unlink()
    elif dest.exists():
        print(f"  skip {dest}: exists and is not the kit's link; leaving it alone", file=sys.stderr)
        return
    dest.symlink_to(src)
    written.append(str(dest))


def write_file(dest: pathlib.Path, text: str, written: list[str]) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and not dest.is_symlink() and GENERATED not in dest.read_text() \
            and "flutter-engineering-kit" not in dest.read_text():
        print(f"  skip {dest}: exists and was not written by the kit", file=sys.stderr)
        return
    if dest.is_symlink():
        dest.unlink()
    dest.write_text(text)
    written.append(str(dest))


def hook_cmd(harness: str, check: str) -> str:
    return f'python3 "{kit_ref() / "hooks" / HOOK_MARK}" {harness} {check}'


# ---------------------------------------------------------------- build

def build_skills() -> pathlib.Path:
    """Copy every skill into the build, adding Codex's agents/openai.yaml to the user-invoked
    ones. Codex ignores disable-model-invocation; this policy is how it keeps them manual."""
    out = BUILD / "skills"
    if out.exists():
        shutil.rmtree(out)
    manual = set(user_invoked())
    for d in skills():
        shutil.copytree(d, out / d.name)
        if d.name in manual:
            desc = field(frontmatter((d / "SKILL.md").read_text())[0], "description")
            (out / d.name / "agents").mkdir(exist_ok=True)
            (out / d.name / "agents" / "openai.yaml").write_text(
                "interface:\n"
                f"  display_name: {json.dumps(d.name)}\n"
                f"  short_description: {json.dumps(desc[:120])}\n"
                "policy:\n"
                "  allow_implicit_invocation: false\n")
    return out


def toml_str(s: str) -> str:
    return json.dumps(s)  # a JSON string is a valid TOML basic string


def convert_agent(src: pathlib.Path, fmt: str, pin: dict | None = None) -> tuple[str, str]:
    """`pin` is this agent's role entry for this harness from models.json. Without one the
    agent inherits the session's model, which is how a cheap job ends up on a frontier model."""
    front, body = frontmatter(src.read_text())
    name, desc = field(front, "name") or src.stem, field(front, "description")
    readonly = not re.search(r"Write|Edit", field(front, "tools"))
    body = body.strip() + "\n"
    model, effort = (pin or {}).get("model"), (pin or {}).get("effort")
    if fmt == "codex-toml":
        lines = [f"name = {toml_str(name)}", f"description = {toml_str(desc)}"]
        if model:
            lines.append(f"model = {toml_str(model)}")
        if effort:
            lines.append(f"model_reasoning_effort = {toml_str(effort)}")
        if readonly:
            lines.append('sandbox_mode = "read-only"')
        lines.append(f"developer_instructions = {toml_str(body)}")
        return f"{name}.toml", "# " + GENERATED.strip("<!-> ") + "\n" + "\n".join(lines) + "\n"
    if fmt == "opencode-md":
        head = ["---", f"description: {desc}", "mode: subagent"]
        if model:
            head.append(f"model: {model}")
        if readonly:
            head += ["permission:", "  edit: deny"]
    elif fmt == "antigravity-md":
        head = ["---", f"name: {name}", f"description: {desc}", f"model: {model or 'inherit'}"]
    else:  # cursor-md
        head = ["---", f"name: {name}", f"description: {desc}"]
        if model:
            head.append(f"model: {model}")
        if readonly:
            head.append("readonly: true")
    return f"{name}.md", "\n".join(head + ["---", "", GENERATED, "", body])


# ---------------------------------------------------------------- models

def role_of(agent: str) -> str | None:
    return next((r for r, spec in ROLES["roles"].items() if agent in spec["agents"]), None)


def load_models() -> dict | None:
    return read_json(MODELS, None)


def pin_for(agent: str, hid: str, models: dict | None) -> dict | None:
    if not models:
        return None
    return (models.get("roles", {}).get(role_of(agent) or "", {}) or {}).get(hid)


def check_models(m) -> list[str]:
    """Every way a models.json can be wrong, so `kit models set` refuses it before anything is
    pinned. Model ids themselves are not checked here: `kit models probe` does that by running one."""
    errs = []
    if not isinstance(m, dict) or m.get("version") != 1:
        return ["models.json needs \"version\": 1"]
    for role, per in (m.get("roles") or {}).items():
        if role not in ROLES["roles"]:
            errs.append(f"unknown role '{role}' (roles: {', '.join(ROLES['roles'])})")
            continue
        for hid, pin in (per or {}).items():
            if hid not in HARNESSES:
                errs.append(f"roles.{role}: unknown harness '{hid}'")
            elif not isinstance(pin, dict) or not str(pin.get("model", "")).strip():
                errs.append(f"roles.{role}.{hid}: needs a \"model\"")
            else:
                allowed = HARNESSES[hid].get("agent_model_values")
                if allowed and pin["model"] not in allowed:
                    errs.append(f"roles.{role}.{hid}: {HARNESSES[hid]['name']} agents take only "
                                f"{', '.join(allowed)}")
                if pin.get("effort") and pin["effort"] not in EFFORTS:
                    errs.append(f"roles.{role}.{hid}: effort '{pin['effort']}' is not one of "
                                f"{', '.join(sorted(EFFORTS))}")
    loop = m.get("loop") or {}
    for key, spec in loop.items():
        if key not in ROLES["loop"] or key.startswith("$"):
            errs.append(f"unknown loop role '{key}' (loop roles: "
                        f"{', '.join(k for k in ROLES['loop'] if not k.startswith('$'))})")
            continue
        hid = (spec or {}).get("harness")
        if hid not in HARNESSES:
            errs.append(f"loop.{key}: unknown harness '{hid}'")
            continue
        ladder = spec.get("ladder")
        if not isinstance(ladder, list) or not ladder:
            errs.append(f"loop.{key}: needs a non-empty \"ladder\" of models, cheapest first")
        if not HARNESSES[hid]["headless"].get("verified") and not m.get("allow_unverified"):
            errs.append(f"loop.{key}: {HARNESSES[hid]['name']}'s headless run is unverified; probe it "
                        f"with `kit models probe {hid} <model>` and set \"allow_unverified\": true")
    b, r = loop.get("builder", {}), loop.get("reviewer", {})
    if b and r and b.get("ladder") and r.get("ladder") and b["ladder"][0] == r["ladder"][0]:
        errs.append("loop: the reviewer starts on the builder's model; pick another family so the "
                    "two do not share blind spots")
    budget = m.get("budget", {})
    for k, v in budget.items():
        if not isinstance(v, (int, float)) or v <= 0:
            errs.append(f"budget.{k}: must be a positive number of dollars")
    if isinstance(budget.get("per_run_usd"), (int, float)) and 0 < budget["per_run_usd"] < 0.25:
        errs.append("budget.per_run_usd: under $0.25 a run can be stopped by its own cold start, "
                    "which loads the harness's whole system prompt before any work")
    return errs


def models_show() -> int:
    m = load_models()
    if not m:
        print("No models configured: kit sub-agents inherit whatever model the session runs.\n"
              "Ask your agent to configure them (the configure-models skill).")
        return 1
    print(f"configured {m.get('configured', '?')}" + (f" · {m['basis']}" if m.get("basis") else ""))
    for role, spec in ROLES["roles"].items():
        per = m.get("roles", {}).get(role, {})
        cells = [f"{h}={p['model']}" + (f"({p['effort']})" if p.get("effort") else "")
                 for h, p in per.items()]
        print(f"  {role:<8} {', '.join(cells) or 'inherits'}   [{', '.join(spec['agents']) or 'loop only'}]")
    for key, spec in (m.get("loop") or {}).items():
        print(f"  loop.{key:<10} {spec['harness']}: {' → '.join(str(s) for s in spec['ladder'])}")
    if m.get("budget"):
        print("  budget   " + ", ".join(f"{k}=${v}" for k, v in m["budget"].items()))
    return 0


KEY_VARS = ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "CODEX_API_KEY", "GEMINI_API_KEY",
            "GOOGLE_API_KEY", "DEEPSEEK_API_KEY", "ZAI_API_KEY", "ZHIPU_API_KEY",
            "OPENROUTER_API_KEY", "CURSOR_API_KEY", "MOONSHOT_API_KEY", "XAI_API_KEY"]


def models_discover() -> int:
    """What this machine can reach, without spending anything: installed harnesses, which
    provider keys are set (names only), and the model list from any CLI that prints one."""
    out = {"harnesses": {}, "keys_set": [k for k in KEY_VARS if os.environ.get(k)],
           "roles": {r: s["needs"] for r, s in ROLES["roles"].items()},
           "current": load_models()}
    for hid in detect():
        h = HARNESSES[hid]
        info = {"cli": next((shutil.which(b) for b in h["detect"]["bins"] if shutil.which(b)), None),
                "headless_verified": bool(h["headless"].get("verified")),
                "agent_model_values": h.get("agent_model_values")}
        if hid == "opencode" and info["cli"]:
            r = subprocess.run([info["cli"], "models"], capture_output=True, text=True, timeout=60)
            info["models"] = r.stdout.split() if r.returncode == 0 else None
        out["harnesses"][hid] = info
    print(json.dumps(out, indent=2))
    return 0


def headless_argv(hid: str, model: str, prompt: str, profile: str, budget: float,
                  effort: str | None = None) -> list[str]:
    t = HARNESSES[hid]["headless"]
    subs = {"{prompt}": prompt, "{model}": model, "{budget}": f"{budget:g}", "{effort}": effort or ""}

    def fill(a: str) -> str:
        for k, v in subs.items():
            a = a.replace(k, v)
        return a
    return ([fill(a) for a in t["argv"]] + ([fill(a) for a in t["effort"]] if effort else [])
            + list(t[profile]) + [fill(a) for a in t["tail"]])


def parse_run(hid: str, stdout: str) -> dict:
    """The run's text, its cost when the harness reports one, and which models answered."""
    t, data = HARNESSES[hid]["headless"], None
    for line in reversed([ln for ln in stdout.strip().splitlines() if ln.strip()] or [""]):
        try:
            data = json.loads(line)
            break
        except json.JSONDecodeError:
            continue
    if data is None:
        try:
            data = json.loads(stdout)
        except json.JSONDecodeError:
            return {"text": stdout, "cost": None, "models": []}
    if not isinstance(data, dict):
        return {"text": stdout, "cost": None, "models": []}
    cost = data.get(t["cost_field"]) if t.get("cost_field") else None
    used = list((data.get(t["models_field"]) or {}).keys()) if t.get("models_field") else []
    text = data.get(t["result_field"]) if t.get("result_field") else None
    return {"text": text if isinstance(text, str) else stdout, "cost": cost, "models": used}


def models_probe(hid: str, model: str, effort: str | None) -> int:
    """Spend a fraction of a cent to prove a model id works through this harness headless,
    and that the model which answered is the one asked for."""
    if hid not in HARNESSES:
        raise SystemExit(f"unknown harness '{hid}'")
    # Not a tiny cap: a cold headless start loads the harness's whole system prompt, which alone
    # can cost several cents. The probe reports what it really spent.
    argv = headless_argv(hid, model, "Reply with the single word: ok", "read", 0.5, effort)
    if not shutil.which(argv[0]):
        print(json.dumps({"ok": False, "error": f"{argv[0]} is not installed"}))
        return 1
    try:
        r = subprocess.run(argv, capture_output=True, text=True, timeout=180)
    except subprocess.TimeoutExpired:
        print(json.dumps({"ok": False, "error": "timed out after 180s"}))
        return 1
    run = parse_run(hid, r.stdout)
    ok = r.returncode == 0 and "ok" in (run["text"] or "").lower()
    print(json.dumps({"ok": ok, "harness": hid, "model": model, "answered_by": run["models"],
                      "cost_usd": run["cost"], "exit": r.returncode,
                      "output": (run["text"] or r.stderr)[-600:]}, indent=2))
    return 0 if ok else 1


def models_set(src: pathlib.Path) -> int:
    m = read_json(src, None)
    errs = check_models(m)
    if errs:
        print("models.json refused:")
        for e in errs:
            print(f"  - {e}")
        return 1
    m.setdefault("configured", __import__("datetime").date.today().isoformat())
    write_json(MODELS, m)
    print(f"saved {MODELS}")
    installed = [h for h in load_record()["harnesses"] if h in HARNESSES]
    if installed:
        install(installed)
    return 0


def models_report() -> int:
    """The loop's cost ledger, by role and model: what configure-models revisits."""
    rows: dict[tuple, dict] = {}
    for f in sorted((STATE / "loop").glob("*/runs.jsonl")):
        for line in f.read_text().splitlines():
            try:
                r = json.loads(line)
            except json.JSONDecodeError:
                continue
            k = (r.get("role"), r.get("harness"), r.get("model"))
            a = rows.setdefault(k, {"runs": 0, "cost": 0.0, "unknown_cost": 0, "failed": 0, "secs": 0})
            a["runs"] += 1
            a["secs"] += r.get("secs", 0)
            a["failed"] += 0 if r.get("ok") else 1
            if r.get("cost_known"):
                a["cost"] += r.get("cost", 0) or 0
            else:
                a["unknown_cost"] += 1
    if not rows:
        print("No loop runs recorded yet.")
        return 0
    print(f"{'role':<10}{'harness':<12}{'model':<34}{'runs':>5}{'failed':>8}{'cost $':>9}{'avg s':>7}")
    for (role, hid, model), a in sorted(rows.items(), key=lambda kv: str(kv[0])):
        cost = f"{a['cost']:.2f}" + ("+?" if a["unknown_cost"] else "")
        print(f"{str(role):<10}{str(hid):<12}{str(model)[:33]:<34}{a['runs']:>5}{a['failed']:>8}"
              f"{cost:>9}{a['secs'] // max(a['runs'], 1):>7}")
    return 0


def opencode_command(name: str) -> str:
    desc = field(frontmatter((KIT / "skills" / name / "SKILL.md").read_text())[0], "description")
    return "\n".join([
        "---", f"description: {desc}", "---", "", GENERATED, "",
        f"Load and follow the `{name}` skill before doing anything else. Call the skill tool "
        f"with name `{name}`, passing the user input below, then follow that skill's "
        "instructions exactly.", "", "User input:", "$ARGUMENTS", ""])


# ---------------------------------------------------------------- hooks per harness

def hook_config(hid: str) -> dict:
    if hid == "codex":
        return {"hooks": {
            "PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "command": hook_cmd("codex", "fixtures")}]}],
            "PostToolUse": [{"matcher": "apply_patch|Edit|Write", "hooks": [{"type": "command", "command": hook_cmd("codex", "format")}]}],
            "UserPromptSubmit": [{"hooks": [{"type": "command", "command": hook_cmd("codex", "secrets")}]}],
        }}
    if hid == "cursor":
        return {"version": 1, "hooks": {
            "beforeShellExecution": [{"command": hook_cmd("cursor", "fixtures")}],
            "afterFileEdit": [{"command": hook_cmd("cursor", "format")}],
            "beforeSubmitPrompt": [{"command": hook_cmd("cursor", "secrets")}],
        }}
    if hid == "antigravity":
        return {"flutter-engineering-kit": {
            "enabled": True,
            "PreToolUse": [{"matcher": "run_command", "hooks": [{"type": "command", "command": hook_cmd("antigravity", "fixtures")}]}],
            "PostToolUse": [{"matcher": "write_to_file|replace_file_content|multi_replace_file_content",
                             "hooks": [{"type": "command", "command": hook_cmd("antigravity", "format")}]}],
        }}
    return {}


def is_ours(entry) -> bool:
    return HOOK_MARK in json.dumps(entry)


def merge_hooks(hid: str, path: pathlib.Path) -> None:
    cfg, ours = read_json(path, {}), hook_config(hid)
    if hid == "antigravity":
        cfg.update(ours)
    else:
        if "version" in ours:
            cfg.setdefault("version", ours["version"])
        events = cfg.setdefault("hooks", {})
        for event, entries in ours["hooks"].items():
            kept = [e for e in events.get(event, []) if not is_ours(e)]
            events[event] = kept + entries
    write_json(path, cfg)


def unmerge_hooks(hid: str, path: pathlib.Path) -> None:
    if not path.exists():
        return
    cfg = read_json(path, {})
    if hid == "antigravity":
        cfg.pop("flutter-engineering-kit", None)
    else:
        events = cfg.get("hooks", {})
        for event in list(events):
            events[event] = [e for e in events[event] if not is_ours(e)]
            if not events[event]:
                del events[event]
    write_json(path, cfg)


def gate_opencode(path: pathlib.Path, on: bool) -> None:
    """opencode ignores disable-model-invocation, so each user-invoked skill gets an `ask`
    gate. Only the kit's own `ask` values are ever removed; a value you changed is yours."""
    cfg = read_json(path, {})
    if on and not path.exists():
        cfg["$schema"] = "https://opencode.ai/config.json"
    perm = cfg.setdefault("permission", {}) if on else cfg.get("permission", {})
    if not isinstance(perm, dict):
        return
    gates = perm.setdefault("skill", {}) if on else perm.get("skill", {})
    if not isinstance(gates, dict):
        return
    for name in user_invoked():
        if on:
            gates.setdefault(name, "ask")
        elif gates.get(name) == "ask":
            del gates[name]
    if not on:
        if "skill" in perm and not perm["skill"]:
            del perm["skill"]
        if "permission" in cfg and not cfg["permission"]:
            del cfg["permission"]
    if cfg or path.exists():
        write_json(path, cfg)


# ---------------------------------------------------------------- install / uninstall

def load_record() -> dict:
    return read_json(RECORD, {"harnesses": {}})


def install_one(hid: str, built: pathlib.Path) -> dict:
    h, written, notes = HARNESSES[hid], [], []
    models = load_models()

    if h["method"] == "plugin":
        # The plugin's agents cannot be edited per user, but a same-named agent in
        # ~/.claude/agents outranks a plugin's, so a pinned model goes there.
        for a in agents():
            pin = pin_for(a.stem, hid, models)
            if pin:
                write_file(HOME / ".claude/agents" / a.name, claude_override(a, pin), written)
        if written:
            notes.append(f"{len(written)} agent(s) pinned to your configured models in ~/.claude/agents")
        cli = shutil.which("claude")
        if cli and not os.environ.get("FLUTTER_KIT_SKIP_CLI"):
            for args in (["plugin", "marketplace", "add", REGISTRY["repo"]],
                         ["plugin", "install", REGISTRY["plugin"]]):
                r = subprocess.run([cli, *args], capture_output=True, text=True)
                if r.returncode != 0 and "already" not in (r.stdout + r.stderr).lower():
                    notes.append(f"`claude {' '.join(args)}` failed: {(r.stderr or r.stdout).strip()[:200]}")
            notes.append("plugin installed; restart Claude Code to load it")
        else:
            notes.append("run inside Claude Code:\n" + "\n".join(
                "      " + line for line in h["install"].splitlines() if not line.startswith("#")))
        return {"written": written, "notes": notes, "plugin": True}

    for d in h.get("skills_dirs", []):
        for skill in sorted(built.iterdir()):
            link(skill, expand(d) / skill.name, written)

    fmt = h.get("agents_format")
    pinned = 0
    for a in agents():
        pin = pin_for(a.stem, hid, models)
        pinned += bool(pin)
        fname, text = convert_agent(a, fmt, pin)
        write_file(expand(h["agents_dir"]) / fname, text, written)
    notes.append(f"{pinned}/{len(agents())} agents pinned to a model" if models
                 else "agents inherit the session's model; configure models to pin cheaper ones")

    if "commands_dir" in h:
        for name in user_invoked():
            write_file(expand(h["commands_dir"]) / f"{name}.md", opencode_command(name), written)
    if "plugins_dir" in h:
        for plug in sorted((KIT / "opencode/plugins").glob("*.ts")):
            link(kit_ref() / "opencode/plugins" / plug.name, expand(h["plugins_dir"]) / plug.name, written)
    if "config_file" in h:
        gate_opencode(expand(h["config_file"]), on=True)
        notes.append(f"{len(user_invoked())} commands gated behind a permission prompt")
    if "hooks_file" in h:
        merge_hooks(hid, expand(h["hooks_file"]))
        notes.append(f"hooks merged into {h['hooks_file']}")
    return {"written": written, "notes": notes}


def claude_override(src: pathlib.Path, pin: dict) -> str:
    front, body = frontmatter(src.read_text())
    lines = [ln for ln in front.splitlines() if not re.match(r"^(model|effort):", ln)]
    lines.append(f"model: {pin['model']}")
    if pin.get("effort"):
        lines.append(f"effort: {pin['effort']}")
    return "---\n" + "\n".join(lines) + "\n---\n\n" + GENERATED + "\n" + body


def still_needed(path: str, record: dict, leaving: set[str]) -> bool:
    return any(path in r.get("written", []) for hid, r in record["harnesses"].items() if hid not in leaving)


def uninstall(ids: list[str]) -> None:
    record = load_record()
    ids = ids or list(record["harnesses"])
    leaving = set(ids)
    for hid in ids:
        r = record["harnesses"].get(hid)
        if not r:
            print(f"{hid}: not installed by the kit")
            continue
        h = HARNESSES[hid]
        if r.get("plugin"):
            for p in r.get("written", []):
                if pathlib.Path(p).is_file():
                    pathlib.Path(p).unlink()
            cli = shutil.which("claude")
            if cli and not os.environ.get("FLUTTER_KIT_SKIP_CLI"):
                subprocess.run([cli, "plugin", "uninstall", REGISTRY["plugin"]], capture_output=True)
                print(f"{hid}: plugin uninstalled")
            else:
                print(f"{hid}: run `/plugin uninstall {REGISTRY['plugin']}` inside Claude Code")
            continue
        removed = 0
        for p in r.get("written", []):
            path = pathlib.Path(p)
            if still_needed(p, record, leaving):
                continue
            if path.is_symlink() or path.is_file():
                path.unlink()
                removed += 1
        if "hooks_file" in h:
            unmerge_hooks(hid, expand(h["hooks_file"]))
        if "config_file" in h:
            gate_opencode(expand(h["config_file"]), on=False)
        print(f"{hid}: removed {removed} kit file(s) and its hook/config entries")
    for hid in ids:
        record["harnesses"].pop(hid, None)
    write_json(RECORD, record)


def detect() -> list[str]:
    found = []
    for hid, h in HARNESSES.items():
        if any(shutil.which(b) for b in h["detect"]["bins"]) or \
                any(expand(d).exists() for d in h["detect"]["dirs"]):
            found.append(hid)
    return found


def install(ids: list[str]) -> None:
    unknown = [i for i in ids if i not in HARNESSES]
    if unknown:
        raise SystemExit(f"unknown harness: {', '.join(unknown)} (choose from {', '.join(HARNESSES)})")
    if not ids:
        raise SystemExit("nothing to install: pass --for <harness,...> or --detect")
    version = json.loads((KIT / ".claude-plugin/plugin.json").read_text())["version"]
    built = build_skills()
    record = load_record()
    record.update({"version": version, "kit": str(kit_ref())})
    print(f"flutter-engineering-kit {version} → {', '.join(HARNESSES[i]['name'] for i in ids)}")
    for hid in ids:
        r = install_one(hid, built)
        record["harnesses"][hid] = r
        print(f"  {HARNESSES[hid]['name']}: {len(r['written'])} file(s)")
        for n in r["notes"]:
            print(f"    - {n}")
    write_json(RECORD, record)
    print("\nNext: open a Flutter project and run /fk-setup once.")
    print("Check the result any time with: kit doctor")


# ---------------------------------------------------------------- doctor / clean-project

def doctor() -> int:
    record, names, problems = load_record(), {d.name for d in skills()}, 0
    print(f"kit:      {KIT}")
    print(f"recorded: {RECORD if RECORD.exists() else 'nothing installed yet'}")
    m = load_models()
    print(f"models:   {'configured ' + m.get('configured', '') if m else 'not configured: sub-agents inherit the session model (ask your agent to configure models)'}")
    for hid, h in HARNESSES.items():
        state = "installed" if hid in record["harnesses"] else "not installed"
        print(f"\n{h['name']} ({state})")
        if h["method"] == "plugin":
            continue
        # Every folder this harness reads skills from, including other harnesses' folders.
        reads = {
            "codex": ["~/.agents/skills", "~/.codex/skills"],
            "opencode": ["~/.config/opencode/skills", "~/.claude/skills", "~/.agents/skills"],
            "cursor": ["~/.agents/skills", "~/.cursor/skills", "~/.claude/skills", "~/.codex/skills"],
            "antigravity": ["~/.gemini/config/skills", "~/.gemini/antigravity-cli/skills"],
        }[hid]
        seen: dict[str, list[str]] = {}
        for d in reads:
            base = expand(d)
            if base.is_dir():
                for s in base.iterdir():
                    if s.name in names:
                        seen.setdefault(s.name, []).append(d)
        dupes = {k: v for k, v in seen.items() if len({d for d in v}) > 1
                 and not (hid == "antigravity")}
        print(f"  skills visible: {len(seen)}/{len(names)}")
        if state == "installed" and len(seen) < len(names):
            problems += 1
            print("  ! some kit skills are missing; re-run `kit install`")
        if dupes:
            problems += 1
            sample = next(iter(dupes.items()))
            print(f"  ! {len(dupes)} skill(s) appear twice, e.g. {sample[0]} in {', '.join(sample[1])}")
        if "hooks_file" in h and state == "installed":
            wired = HOOK_MARK in (expand(h["hooks_file"]).read_text() if expand(h["hooks_file"]).exists() else "")
            print(f"  hooks: {'wired' if wired else 'MISSING'}")
            problems += 0 if wired else 1
    print(f"\n{'all good' if not problems else f'{problems} problem(s) found'}")
    return 1 if problems else 0


# Skill names earlier kit versions used, so clean-project still recognises their copies.
RETIRED_SKILLS = {"setup-flutter-project", "flutter-implement", "flutter-create-feature",
                  "flutter-create-feature-e2e", "flutter-create-screen-e2e"}


def clean_project(target: pathlib.Path) -> None:
    """Remove the per-project mirrors earlier kit versions wrote. Only kit-named paths go."""
    names = {d.name for d in skills()} | RETIRED_SKILLS
    agent_files = {a.name for a in agents()}
    removed = []
    for base in (".opencode", ".cursor", ".claude"):
        root = target / base
        for n in names:
            for p in (root / "skills" / n, root / "commands" / f"{n}.md"):
                if p.is_dir():
                    shutil.rmtree(p)
                    removed.append(p)
                elif p.is_file():
                    p.unlink()
                    removed.append(p)
        for a in agent_files:
            p = root / "agents" / a
            if p.is_file():
                p.unlink()
                removed.append(p)
        for extra in ("template", "plugins/flutter-kit.ts", "README.md"):
            p = root / extra
            if p.is_dir() and base != ".claude":
                shutil.rmtree(p)
                removed.append(p)
            elif p.is_file() and (extra != "README.md" or "Generated mirror" in p.read_text()):
                p.unlink()
                removed.append(p)
    cfg_path = target / "opencode.json"
    if cfg_path.exists():
        gate_opencode(cfg_path, on=False)
        cfg = read_json(cfg_path, {})
        instr = cfg.get("instructions")
        if isinstance(instr, list) and ".opencode/rules/*.md" in instr:
            cfg["instructions"] = [i for i in instr if i != ".opencode/rules/*.md"] or None
            if cfg["instructions"] is None:
                del cfg["instructions"]
            write_json(cfg_path, cfg)
    print(f"removed {len(removed)} kit path(s) from {target}")
    for p in removed:
        print(f"  - {p.relative_to(target)}")


def main() -> int:
    ap = argparse.ArgumentParser(prog="kit", description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    i = sub.add_parser("install")
    i.add_argument("--for", dest="harnesses", default="")
    i.add_argument("--detect", action="store_true")
    u = sub.add_parser("uninstall")
    u.add_argument("--for", dest="harnesses", default="")
    sub.add_parser("doctor")
    sub.add_parser("list")
    c = sub.add_parser("clean-project")
    c.add_argument("path")
    m = sub.add_parser("models")
    m.add_argument("action", choices=["show", "discover", "probe", "set", "report"])
    m.add_argument("args", nargs="*")
    m.add_argument("--effort")
    lp = sub.add_parser("loop")
    lp.add_argument("action", choices=["run", "status"])
    lp.add_argument("path", nargs="?", default=".")
    lp.add_argument("--watch", type=int, metavar="SECONDS", help="tick every SECONDS until stopped")
    lp.add_argument("--dry-run", action="store_true", help="say what would run; run nothing")
    lp.add_argument("--no-build", action="store_true", help="drive open PRs only; start no tickets")
    a = ap.parse_args()
    ids = [x.strip() for x in getattr(a, "harnesses", "").split(",") if x.strip()]
    if a.cmd == "install":
        install(sorted(set(ids + (detect() if a.detect else [])), key=list(HARNESSES).index))
    elif a.cmd == "uninstall":
        uninstall(ids)
    elif a.cmd == "doctor":
        return doctor()
    elif a.cmd == "list":
        found = set(detect())
        for hid, h in HARNESSES.items():
            print(f"{hid:<12} {h['name']:<12} {'detected' if hid in found else ''}")
    elif a.cmd == "clean-project":
        clean_project(pathlib.Path(a.path).resolve())
    elif a.cmd == "models":
        if a.action == "probe":
            if len(a.args) != 2:
                raise SystemExit("usage: kit models probe <harness> <model> [--effort level]")
            return models_probe(a.args[0], a.args[1], a.effort)
        if a.action == "set":
            if len(a.args) != 1:
                raise SystemExit("usage: kit models set <models.json>")
            return models_set(pathlib.Path(a.args[0]))
        return {"show": models_show, "discover": models_discover, "report": models_report}[a.action]()
    elif a.cmd == "loop":
        import kitloop
        return kitloop.main(a, sys.modules[__name__])
    return 0


if __name__ == "__main__":
    sys.exit(main())
