#!/usr/bin/env python3
"""Install the kit once per user, for whichever agent harnesses you use.

    kit install --for codex,opencode      install for these harnesses
    kit install --detect                  install for every harness found on this machine
    kit doctor                            show what each harness will see
    kit uninstall [--for codex]           remove exactly what was installed (default: all)
    kit clean-project /path/to/app        remove an old per-project mirror (.opencode/.cursor/.claude)

Skills live in one place per harness family, never inside a project. Claude Code installs
as the managed plugin; every other harness gets the skills linked from a generated build
under ~/.flutter-kit/build, plus its own agents, commands and hooks in the shape it reads.
install/harnesses.json is the registry of paths; ~/.flutter-kit/installed.json records
everything written, so uninstall removes exactly that and nothing of yours.

Environment: FLUTTER_KIT_HOME (default ~/.flutter-kit), HOME (tests point it elsewhere),
FLUTTER_KIT_SKIP_CLI=1 (never shell out to `claude`; tests set it).
"""

import argparse
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys

KIT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = json.loads((KIT / "install/harnesses.json").read_text())
HARNESSES = {h["id"]: h for h in REGISTRY["harnesses"]}
HOME = pathlib.Path(os.environ.get("HOME", str(pathlib.Path.home())))
STATE = pathlib.Path(os.environ.get("FLUTTER_KIT_HOME", str(HOME / ".flutter-kit")))
BUILD = STATE / "build"
RECORD = STATE / "installed.json"
HOOK_MARK = "kit-hook.py"
GENERATED = "<!-- Generated by flutter-engineering-kit (scripts/kit.py). Re-run `kit install` instead of editing. -->"


# ---------------------------------------------------------------- helpers

def expand(p: str) -> pathlib.Path:
    return HOME / p[2:] if p.startswith("~/") else pathlib.Path(p)


def kit_ref() -> pathlib.Path:
    """The path installed files point at. Through ~/.flutter-kit/current when this run comes
    from there, so `kit update` re-points one symlink instead of rewriting every hook."""
    current = STATE / "current"
    if current.is_symlink() and current.resolve() == KIT:
        return current
    return KIT


def frontmatter(text: str) -> tuple[str, str]:
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    return (m.group(1), m.group(2)) if m else ("", text)


def field(front: str, key: str) -> str:
    m = re.search(rf"^{key}:\s*(.+)$", front, re.M)
    return m.group(1).strip().strip('"') if m else ""


def skills() -> list[pathlib.Path]:
    return sorted(p.parent for p in (KIT / "skills").glob("*/SKILL.md"))


def user_invoked() -> list[str]:
    return [d.name for d in skills()
            if "disable-model-invocation: true" in frontmatter((d / "SKILL.md").read_text())[0]]


def agents() -> list[pathlib.Path]:
    return sorted(p for p in (KIT / "agents").glob("*.md") if p.name != "README.md")


def read_json(path: pathlib.Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return json.loads(strip_jsonc(path.read_text()))


def write_json(path: pathlib.Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def strip_jsonc(text: str) -> str:
    out, i, n, in_str, esc = [], 0, len(text), False, False
    while i < n:
        c = text[i]
        if in_str:
            out.append(c)
            esc = (not esc) and c == "\\"
            if c == '"' and not esc:
                in_str = False
            i += 1
        elif c == '"':
            in_str = True
            out.append(c)
            i += 1
        elif text.startswith("//", i):
            while i < n and text[i] != "\n":
                i += 1
        elif text.startswith("/*", i):
            end = text.find("*/", i + 2)
            i = n if end < 0 else end + 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def link(src: pathlib.Path, dest: pathlib.Path, written: list[str]) -> None:
    """Symlink dest -> src. Refuses to replace anything that is not already our link."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.is_symlink():
        dest.unlink()
    elif dest.exists():
        print(f"  skip {dest}: exists and is not the kit's link; leaving it alone", file=sys.stderr)
        return
    dest.symlink_to(src)
    written.append(str(dest))


def write_file(dest: pathlib.Path, text: str, written: list[str]) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and not dest.is_symlink() and GENERATED not in dest.read_text() \
            and "flutter-engineering-kit" not in dest.read_text():
        print(f"  skip {dest}: exists and was not written by the kit", file=sys.stderr)
        return
    if dest.is_symlink():
        dest.unlink()
    dest.write_text(text)
    written.append(str(dest))


def hook_cmd(harness: str, check: str) -> str:
    return f'python3 "{kit_ref() / "hooks" / HOOK_MARK}" {harness} {check}'


# ---------------------------------------------------------------- build

def build_skills() -> pathlib.Path:
    """Copy every skill into the build, adding Codex's agents/openai.yaml to the user-invoked
    ones. Codex ignores disable-model-invocation; this policy is how it keeps them manual."""
    out = BUILD / "skills"
    if out.exists():
        shutil.rmtree(out)
    manual = set(user_invoked())
    for d in skills():
        shutil.copytree(d, out / d.name)
        if d.name in manual:
            desc = field(frontmatter((d / "SKILL.md").read_text())[0], "description")
            (out / d.name / "agents").mkdir(exist_ok=True)
            (out / d.name / "agents" / "openai.yaml").write_text(
                "interface:\n"
                f"  display_name: {json.dumps(d.name)}\n"
                f"  short_description: {json.dumps(desc[:120])}\n"
                "policy:\n"
                "  allow_implicit_invocation: false\n")
    return out


def toml_str(s: str) -> str:
    return json.dumps(s)  # a JSON string is a valid TOML basic string


def convert_agent(src: pathlib.Path, fmt: str) -> tuple[str, str]:
    front, body = frontmatter(src.read_text())
    name, desc = field(front, "name") or src.stem, field(front, "description")
    readonly = not re.search(r"Write|Edit", field(front, "tools"))
    body = body.strip() + "\n"
    if fmt == "codex-toml":
        lines = [f"name = {toml_str(name)}", f"description = {toml_str(desc)}"]
        if readonly:
            lines.append('sandbox_mode = "read-only"')
        lines.append(f"developer_instructions = {toml_str(body)}")
        return f"{name}.toml", "# " + GENERATED.strip("<!-> ") + "\n" + "\n".join(lines) + "\n"
    if fmt == "opencode-md":
        head = ["---", f"description: {desc}", "mode: subagent"]
        if readonly:
            head += ["permission:", "  edit: deny"]
    elif fmt == "antigravity-md":
        head = ["---", f"name: {name}", f"description: {desc}", "model: inherit"]
    else:  # cursor-md
        head = ["---", f"name: {name}", f"description: {desc}"]
        if readonly:
            head.append("readonly: true")
    return f"{name}.md", "\n".join(head + ["---", "", GENERATED, "", body])


def opencode_command(name: str) -> str:
    desc = field(frontmatter((KIT / "skills" / name / "SKILL.md").read_text())[0], "description")
    return "\n".join([
        "---", f"description: {desc}", "---", "", GENERATED, "",
        f"Load and follow the `{name}` skill before doing anything else. Call the skill tool "
        f"with name `{name}`, passing the user input below, then follow that skill's "
        "instructions exactly.", "", "User input:", "$ARGUMENTS", ""])


# ---------------------------------------------------------------- hooks per harness

def hook_config(hid: str) -> dict:
    if hid == "codex":
        return {"hooks": {
            "PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "command": hook_cmd("codex", "fixtures")}]}],
            "PostToolUse": [{"matcher": "apply_patch|Edit|Write", "hooks": [{"type": "command", "command": hook_cmd("codex", "format")}]}],
            "UserPromptSubmit": [{"hooks": [{"type": "command", "command": hook_cmd("codex", "secrets")}]}],
        }}
    if hid == "cursor":
        return {"version": 1, "hooks": {
            "beforeShellExecution": [{"command": hook_cmd("cursor", "fixtures")}],
            "afterFileEdit": [{"command": hook_cmd("cursor", "format")}],
            "beforeSubmitPrompt": [{"command": hook_cmd("cursor", "secrets")}],
        }}
    if hid == "antigravity":
        return {"flutter-engineering-kit": {
            "enabled": True,
            "PreToolUse": [{"matcher": "run_command", "hooks": [{"type": "command", "command": hook_cmd("antigravity", "fixtures")}]}],
            "PostToolUse": [{"matcher": "write_to_file|replace_file_content|multi_replace_file_content",
                             "hooks": [{"type": "command", "command": hook_cmd("antigravity", "format")}]}],
        }}
    return {}


def is_ours(entry) -> bool:
    return HOOK_MARK in json.dumps(entry)


def merge_hooks(hid: str, path: pathlib.Path) -> None:
    cfg, ours = read_json(path, {}), hook_config(hid)
    if hid == "antigravity":
        cfg.update(ours)
    else:
        if "version" in ours:
            cfg.setdefault("version", ours["version"])
        events = cfg.setdefault("hooks", {})
        for event, entries in ours["hooks"].items():
            kept = [e for e in events.get(event, []) if not is_ours(e)]
            events[event] = kept + entries
    write_json(path, cfg)


def unmerge_hooks(hid: str, path: pathlib.Path) -> None:
    if not path.exists():
        return
    cfg = read_json(path, {})
    if hid == "antigravity":
        cfg.pop("flutter-engineering-kit", None)
    else:
        events = cfg.get("hooks", {})
        for event in list(events):
            events[event] = [e for e in events[event] if not is_ours(e)]
            if not events[event]:
                del events[event]
    write_json(path, cfg)


def gate_opencode(path: pathlib.Path, on: bool) -> None:
    """opencode ignores disable-model-invocation, so each user-invoked skill gets an `ask`
    gate. Only the kit's own `ask` values are ever removed; a value you changed is yours."""
    cfg = read_json(path, {})
    if on and not path.exists():
        cfg["$schema"] = "https://opencode.ai/config.json"
    perm = cfg.setdefault("permission", {}) if on else cfg.get("permission", {})
    if not isinstance(perm, dict):
        return
    gates = perm.setdefault("skill", {}) if on else perm.get("skill", {})
    if not isinstance(gates, dict):
        return
    for name in user_invoked():
        if on:
            gates.setdefault(name, "ask")
        elif gates.get(name) == "ask":
            del gates[name]
    if not on:
        if "skill" in perm and not perm["skill"]:
            del perm["skill"]
        if "permission" in cfg and not cfg["permission"]:
            del cfg["permission"]
    if cfg or path.exists():
        write_json(path, cfg)


# ---------------------------------------------------------------- install / uninstall

def load_record() -> dict:
    return read_json(RECORD, {"harnesses": {}})


def install_one(hid: str, built: pathlib.Path) -> dict:
    h, written, notes = HARNESSES[hid], [], []

    if h["method"] == "plugin":
        cli = shutil.which("claude")
        if cli and not os.environ.get("FLUTTER_KIT_SKIP_CLI"):
            for args in (["plugin", "marketplace", "add", REGISTRY["repo"]],
                         ["plugin", "install", REGISTRY["plugin"]]):
                r = subprocess.run([cli, *args], capture_output=True, text=True)
                if r.returncode != 0 and "already" not in (r.stdout + r.stderr).lower():
                    notes.append(f"`claude {' '.join(args)}` failed: {(r.stderr or r.stdout).strip()[:200]}")
            notes.append("plugin installed; restart Claude Code to load it")
        else:
            notes.append("run inside Claude Code:\n" + "\n".join(
                "      " + line for line in h["install"].splitlines() if not line.startswith("#")))
        return {"written": written, "notes": notes, "plugin": True}

    for d in h.get("skills_dirs", []):
        for skill in sorted(built.iterdir()):
            link(skill, expand(d) / skill.name, written)

    fmt = h.get("agents_format")
    for a in agents():
        fname, text = convert_agent(a, fmt)
        write_file(expand(h["agents_dir"]) / fname, text, written)

    if "commands_dir" in h:
        for name in user_invoked():
            write_file(expand(h["commands_dir"]) / f"{name}.md", opencode_command(name), written)
    if "plugins_dir" in h:
        for plug in sorted((KIT / "opencode/plugins").glob("*.ts")):
            link(kit_ref() / "opencode/plugins" / plug.name, expand(h["plugins_dir"]) / plug.name, written)
    if "config_file" in h:
        gate_opencode(expand(h["config_file"]), on=True)
        notes.append(f"{len(user_invoked())} commands gated behind a permission prompt")
    if "hooks_file" in h:
        merge_hooks(hid, expand(h["hooks_file"]))
        notes.append(f"hooks merged into {h['hooks_file']}")
    return {"written": written, "notes": notes}


def still_needed(path: str, record: dict, leaving: set[str]) -> bool:
    return any(path in r.get("written", []) for hid, r in record["harnesses"].items() if hid not in leaving)


def uninstall(ids: list[str]) -> None:
    record = load_record()
    ids = ids or list(record["harnesses"])
    leaving = set(ids)
    for hid in ids:
        r = record["harnesses"].get(hid)
        if not r:
            print(f"{hid}: not installed by the kit")
            continue
        h = HARNESSES[hid]
        if r.get("plugin"):
            cli = shutil.which("claude")
            if cli and not os.environ.get("FLUTTER_KIT_SKIP_CLI"):
                subprocess.run([cli, "plugin", "uninstall", REGISTRY["plugin"]], capture_output=True)
                print(f"{hid}: plugin uninstalled")
            else:
                print(f"{hid}: run `/plugin uninstall {REGISTRY['plugin']}` inside Claude Code")
            continue
        removed = 0
        for p in r.get("written", []):
            path = pathlib.Path(p)
            if still_needed(p, record, leaving):
                continue
            if path.is_symlink() or path.is_file():
                path.unlink()
                removed += 1
        if "hooks_file" in h:
            unmerge_hooks(hid, expand(h["hooks_file"]))
        if "config_file" in h:
            gate_opencode(expand(h["config_file"]), on=False)
        print(f"{hid}: removed {removed} kit file(s) and its hook/config entries")
    for hid in ids:
        record["harnesses"].pop(hid, None)
    write_json(RECORD, record)


def detect() -> list[str]:
    found = []
    for hid, h in HARNESSES.items():
        if any(shutil.which(b) for b in h["detect"]["bins"]) or \
                any(expand(d).exists() for d in h["detect"]["dirs"]):
            found.append(hid)
    return found


def install(ids: list[str]) -> None:
    unknown = [i for i in ids if i not in HARNESSES]
    if unknown:
        raise SystemExit(f"unknown harness: {', '.join(unknown)} (choose from {', '.join(HARNESSES)})")
    if not ids:
        raise SystemExit("nothing to install: pass --for <harness,...> or --detect")
    version = json.loads((KIT / ".claude-plugin/plugin.json").read_text())["version"]
    built = build_skills()
    record = load_record()
    record.update({"version": version, "kit": str(kit_ref())})
    print(f"flutter-engineering-kit {version} → {', '.join(HARNESSES[i]['name'] for i in ids)}")
    for hid in ids:
        r = install_one(hid, built)
        record["harnesses"][hid] = r
        print(f"  {HARNESSES[hid]['name']}: {len(r['written'])} file(s)")
        for n in r["notes"]:
            print(f"    - {n}")
    write_json(RECORD, record)
    print("\nNext: open a Flutter project and run /setup-flutter-project once.")
    print("Check the result any time with: kit doctor")


# ---------------------------------------------------------------- doctor / clean-project

def doctor() -> int:
    record, names, problems = load_record(), {d.name for d in skills()}, 0
    print(f"kit:      {KIT}")
    print(f"recorded: {RECORD if RECORD.exists() else 'nothing installed yet'}")
    for hid, h in HARNESSES.items():
        state = "installed" if hid in record["harnesses"] else "not installed"
        print(f"\n{h['name']} ({state})")
        if h["method"] == "plugin":
            continue
        # Every folder this harness reads skills from, including other harnesses' folders.
        reads = {
            "codex": ["~/.agents/skills", "~/.codex/skills"],
            "opencode": ["~/.config/opencode/skills", "~/.claude/skills", "~/.agents/skills"],
            "cursor": ["~/.agents/skills", "~/.cursor/skills", "~/.claude/skills", "~/.codex/skills"],
            "antigravity": ["~/.gemini/config/skills", "~/.gemini/antigravity-cli/skills"],
        }[hid]
        seen: dict[str, list[str]] = {}
        for d in reads:
            base = expand(d)
            if base.is_dir():
                for s in base.iterdir():
                    if s.name in names:
                        seen.setdefault(s.name, []).append(d)
        dupes = {k: v for k, v in seen.items() if len({d for d in v}) > 1
                 and not (hid == "antigravity")}
        print(f"  skills visible: {len(seen)}/{len(names)}")
        if state == "installed" and len(seen) < len(names):
            problems += 1
            print("  ! some kit skills are missing; re-run `kit install`")
        if dupes:
            problems += 1
            sample = next(iter(dupes.items()))
            print(f"  ! {len(dupes)} skill(s) appear twice, e.g. {sample[0]} in {', '.join(sample[1])}")
        if "hooks_file" in h and state == "installed":
            wired = HOOK_MARK in (expand(h["hooks_file"]).read_text() if expand(h["hooks_file"]).exists() else "")
            print(f"  hooks: {'wired' if wired else 'MISSING'}")
            problems += 0 if wired else 1
    print(f"\n{'all good' if not problems else f'{problems} problem(s) found'}")
    return 1 if problems else 0


def clean_project(target: pathlib.Path) -> None:
    """Remove the per-project mirrors earlier kit versions wrote. Only kit-named paths go."""
    names = {d.name for d in skills()} | set(user_invoked())
    agent_files = {a.name for a in agents()}
    removed = []
    for base in (".opencode", ".cursor", ".claude"):
        root = target / base
        for n in names:
            for p in (root / "skills" / n, root / "commands" / f"{n}.md"):
                if p.is_dir():
                    shutil.rmtree(p)
                    removed.append(p)
                elif p.is_file():
                    p.unlink()
                    removed.append(p)
        for a in agent_files:
            p = root / "agents" / a
            if p.is_file():
                p.unlink()
                removed.append(p)
        for extra in ("template", "plugins/flutter-kit.ts", "README.md"):
            p = root / extra
            if p.is_dir() and base != ".claude":
                shutil.rmtree(p)
                removed.append(p)
            elif p.is_file() and (extra != "README.md" or "Generated mirror" in p.read_text()):
                p.unlink()
                removed.append(p)
    cfg_path = target / "opencode.json"
    if cfg_path.exists():
        gate_opencode(cfg_path, on=False)
        cfg = read_json(cfg_path, {})
        instr = cfg.get("instructions")
        if isinstance(instr, list) and ".opencode/rules/*.md" in instr:
            cfg["instructions"] = [i for i in instr if i != ".opencode/rules/*.md"] or None
            if cfg["instructions"] is None:
                del cfg["instructions"]
            write_json(cfg_path, cfg)
    print(f"removed {len(removed)} kit path(s) from {target}")
    for p in removed:
        print(f"  - {p.relative_to(target)}")


def main() -> int:
    ap = argparse.ArgumentParser(prog="kit", description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    i = sub.add_parser("install")
    i.add_argument("--for", dest="harnesses", default="")
    i.add_argument("--detect", action="store_true")
    u = sub.add_parser("uninstall")
    u.add_argument("--for", dest="harnesses", default="")
    sub.add_parser("doctor")
    sub.add_parser("list")
    c = sub.add_parser("clean-project")
    c.add_argument("path")
    a = ap.parse_args()
    ids = [x.strip() for x in getattr(a, "harnesses", "").split(",") if x.strip()]
    if a.cmd == "install":
        install(sorted(set(ids + (detect() if a.detect else [])), key=list(HARNESSES).index))
    elif a.cmd == "uninstall":
        uninstall(ids)
    elif a.cmd == "doctor":
        return doctor()
    elif a.cmd == "list":
        found = set(detect())
        for hid, h in HARNESSES.items():
            print(f"{hid:<12} {h['name']:<12} {'detected' if hid in found else ''}")
    elif a.cmd == "clean-project":
        clean_project(pathlib.Path(a.path).resolve())
    return 0


if __name__ == "__main__":
    sys.exit(main())
